### ISSUE TITLE
copy() of a Munch gives dict() object

### ISSUE THREAD

**Issue by nivw** [Infinidat/munch#10]
import munch
x=munch.Munch()
type(x.copy())
--> dict

I want this to give me a munch object

**Comment by lballan** [comment]
import munch
x=munch.Munch()
cp=x.copy()
y=munch.Munch(cp)

type(y) —> munch.Munch

**Comment by omergertel** [comment]
Having a workaround is not the same as having a solution. 
I think `copy` should generally return the correct type. I'm re-opening.

**Comment by wiggin15** [comment]
Fixed.
