### ISSUE TITLE
There is no __dict__ attribute on an object that inherits from Munch

### ISSUE THREAD

**Issue by bobh66** [Infinidat/munch#19]
If I define an object that inherits from Munch:

class Foo(Munch):
    def __init__(self, bar):
       self.bar = bar

and then do:

myfoo = Foo("mybar")

the resulting myfoo object has no __dict__ attribute, so while I can do myfoo.toDict(), I can't do myfoo.__dict__ which would be nice to allow it to be treated like any other object.

@property
def __dict__(self):
    return self.toDict()

would allow myfoo.__dict__ to work the same way as toDict()

**Comment by episodeyang** [comment]
@vmalloc is there any issue with this approach? If possible I would like to have this merged and published soon.

**Comment by vmalloc** [comment]
@episodeyang The approach is fine - it just took me some time to get to it because I was swamped with other things. Thanks a lot for contributing!

**Comment by episodeyang** [comment]
@vmalloc Thanks!

Afterward I realized that I had a similar library called `waterbear`, so I spend good part of tonight adding these features to it. 😄

**Comment by ayalash** [comment]
This issue was fixed by https://github.com/Infinidat/munch/pull/20 (which was merged a long time ago). Closing...
