### ISSUE TITLE
use toDict() with __dict__ custom getter to allow getting the dictionary via `vars(munch)`

### ISSUE THREAD

**Issue by episodeyang** [Infinidat/munch#21]
It would be great if the standard python `vars(obj)` and the `__dict__` attributes are respected, so that Munch instances could be used in a standard way.

The `toDict()` syntax is not standard, and causes the implementation to leak through abstraction layers.

Thanks for this library!

**Comment by episodeyang** [comment]
I want to correct th previous post: it shouldn't be the `__dict__` method b/c it is only use for introspection in python.

It should be the `__vars__` method instead.

**Comment by episodeyang** [comment]
Yikes, my python meta programming knowledge is a mess. 

Really `vars` returns `obj.__dict__`, so in order for `vars(munch)` to work, we either need to change how munch treats the `self.__dict__` property, or overload it via attribute getter.

@vmalloc What's your thought on this?

**Comment by vmalloc** [comment]
I believe so. Closing.
