### ISSUE TITLE
Accessing serialized json with numeric string as keys

### ISSUE THREAD

**Issue by nadavgut** [Infinidat/munch#24]
hi
Consider the following case:
```
from munch import munchify

INFO = munchify({
        "1234": {
            "first_name": "munch",
            "last_name": "munchi"
        }})

INFO.1234
```
You get as a result: 
```
File "<stdin>", line 1
    INFO.1234
                    ^
SyntaxError: invalid syntax
```
Is there any intention to support numeric values?

**Comment by vmalloc** [comment]
This is actually a limitation of Python itself. Note that you're getting a syntax error, and not a runtime error.

You'll actually get this even if the object you're trying it on doesn't exist:

```
>>> nonexisting.123
  File "<stdin>", line 1
    nonexisting.123
        ^
SyntaxError: invalid syntax
```
