### ISSUE TITLE
Please publish python universal wheel

### ISSUE THREAD

**Issue by pabelanger** [Infinidat/munch#31]
**What are wheels?**
Wheels are the new standard of Python distribution and are intended to replace eggs. Support is offered in pip >= 1.4 and setuptools >= 0.8.

**Advantages of wheels**
Faster installation for pure Python and native C extension packages.
Avoids arbitrary code execution for installation. (Avoids setup.py)
Installation of a C extension does not require a compiler on Windows or macOS.
Allows better caching for testing and continuous integration.
Creates .pyc files as part of installation to ensure they match the Python interpreter used.
More consistent installs across platforms and machines.

https://pythonwheels.com/

Must appreciated!

**Comment by vmalloc** [comment]
@pabelanger thank you for the info! I don't see myself getting to it any time soon, so PRs adding this to the Travis deployment are very much welcome!

**Comment by pabelanger** [comment]
Done, I'm guess travis will do the right thing once you tag the next release.

**Comment by vmalloc** [comment]
Thanks!

**Comment by pabelanger** [comment]
Great, thanks for merging. Do you have any ETA on when your next tag / release would be?  Like I said, I didn't actually test that travis.ci will do the right thing, I'm assuming since you were already doing bdist_wheel in your yaml file

**Comment by vmalloc** [comment]
@pabelanger I'm releasing a minor version now to see if it works (2.3.2)

**Comment by vmalloc** [comment]
@pabelanger Doesn't seem to be working. 2.3.2 was uploaded to pypi but no wheels...

**Comment by pabelanger** [comment]
Do you know where I can few the build logs of travis when you tagged the release? I am guessing it was travis-ci that actually published the files to pypi.

**Comment by pabelanger** [comment]
okay, I see the issue, there is a typo:

https://github.com/Infinidat/munch/pull/33
