### ISSUE TITLE
Deserializing a munchified object makes it an dict

### ISSUE THREAD

**Issue by kannangce** [Infinidat/munch#37]
I am trying to create an `Munch` object and when I serialize it to JSON and deserialize it, I am getting an dict, rather than an object.

`a = Munch(status_code= 200, text= {'code': '1234'})`

`a.status_code # result 200`

`a_js=json.dumps(a)`

`json.loads(a_js).status_code # AttributeError: 'dict' object has no attribute 'status_code'`

**Comment by vmalloc** [comment]
@kannangce `json.dumps` and `json.loads` are lossy - they do not preserve the exact original type specified, and in many cases (through custom decoders/encoders) lose the original values fed to them.

I'm guessing you're confusing `json` with a stricter serialization/deserialization scheme such as `pickle` which, although not human-readalbe, does guarantee preserving the original type

**Comment by vmalloc** [comment]
Also, I'd like to point out that the only reason `json.dumps` works on munches is the fact that they inherit from dict. Otherwise, you'd have gotten a `ValueError` and would have been required to implement a custom encoder for it anyway

**Comment by ayalash** [comment]
Closing this issue due to @vmalloc comments.

@kannangce as commented above, the functions you used are lossy, so there is no option to fix it (not a munch bug).

The closes option I have to offer you, is to use `Munch.fromJSON` method (was added by https://github.com/Infinidat/munch/pull/55):
```
a = Munch(status_code= 200, text={'code': '1234'})
a.status_code # result 200
a_js = a.toJSON()
Munch.fromJSON(a_js).status_code # result 200
```
