### ISSUE TITLE
Key with Python reserved names like "for"

### ISSUE THREAD

**Issue by JulianS-Uni** [Infinidat/munch#42]
I have an dictionary which i like to convert to a Munch. The problem is, that my dictionary has a key named "for" which results in a Munch.for attrubite, which is not callable because "for" is a reserved keyword of Python.
What do you think about manipulating the dictionary keys inside the Munch class so that they can not be one of the Python keywords which you can get by `keyword.kwlist`.

Instead altering those dictionary keys to `_for`, `_else` etc.
I know this is a very specific problem and you can workaround this by calling `Munch.get("for")` but i think it is super weird to generate those attributes in the first place.

For some background:
Im getting a dictionary from the [streamlabs API](https://dev.streamlabs.com/docs/socket-api)
```
{
  "type": "follow",
  "message": [
    {
      "created_at": "2017-08-22 00:14:35",
      "id": "170884026",
      "name": "h4r5h48002",
      "_id": "74a0b93e736f1f14762111f8ae34bf42"
    }
  ],
  "for": "twitch_account"
}
```

**Comment by vmalloc** [comment]
I don't think changing key names is a reasonable thing to do, especially given the possibility of your original dictionary already has a key of the target name, e.g.:
```python
{
  "for": "a",
  "_for": "b",
}
```
Unfortunately I don't see any way Munch can solve this type of issues. Given that Munch also mimics a dictionary, you don't have to call `.get`, but can use item access (e.g. `m['for']`) as well.
