### ISSUE TITLE
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!munch.Munch'

### ISSUE THREAD

**Issue by duongnt** [Infinidat/munch#44]
This happens with PyYAML 5.1.

The fix seems to be adding `Loader=yaml.FullLoader` to `yaml.load`, or use `yaml.full_load` instead: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

**Comment by zeeMonkeez** [comment]
This does not seem to fix the issue for me.

```
import yaml
import munch

d = munch.Munch({'q':42})
print(d)
s = yaml.dump(d)
print(s)
d2 = yaml.full_load(s)
print(d2)
```

This is with PyYAML at 5.1.2, munch at 2.3.2.
