### ISSUE TITLE
A Bunch implementation should belongs to an organization

### ISSUE THREAD

**Issue by femtotrader** [Infinidat/munch#5]
Hello,

I think A Bunch like implementation this should belongs to an organization
in order to avoid same future that dsc/bunch.

See also https://github.com/F483/neobunch/issues/2
CC: @vmalloc @F483

Kind regards

**Comment by vmalloc** [comment]
@femtotrader well dsc/bunch belonged to a single developer, who just stopped caring. Munch is currently in the Infinidat organization, with a few dozens of developers listening and watching. I think we're fine for now.

It is also slightly an overkill IMO to set up an organization for such a small library.

**Comment by vmalloc** [comment]
And of course - any involvement in PRs/feature requests/suggestions/bugs is more than welcome at this point, so feel free

**Comment by femtotrader** [comment]
Thanks @vmalloc that's clear. I wanted @F483 to be aware of this.
