### ISSUE TITLE
is Munch thread safe for reading?

### ISSUE THREAD

**Issue by andrewxi19** [Infinidat/munch#59]
We are using munch for a service hosted in IIS.  Due to the large size of the data (17GB) in munch, only one python instance can be created through Flask under IIS.   Now the question is, would the munch support multiple calls almost simultaneously from different users through Flask APIs without the worry on thread race.

**Comment by ayalash** [comment]
@andrewxi19 There is no special handling in Munch for multi-threading, so it is not thread safe.
