### ISSUE TITLE
Undeclared dependency on setuptools (pkg_resources)

### ISSUE THREAD

**Issue by jaraco** [Infinidat/munch#67]
On a system without Setuptools pre-installed, munch fails on import:

```
~ $ pip-run munch -- -c "import munch"
Collecting munch
  Using cached munch-2.5.0-py2.py3-none-any.whl (10 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, munch
Successfully installed munch-2.5.0 six-1.15.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-y4m51iwb/munch/__init__.py", line 24, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

The project should remove use of pkg_resources or declare the dependency on setuptools.

**Comment by jaraco** [comment]
Looks like this issue was incidentally addressed in #64, but the latest version in PyPI still has the bug. A new release would fix it. This undeclared dependency may also be part of the confusion that led to #60 and #61.

**Comment by bwcjanes** [comment]
Time to move on from pkg_resources altogether...

>   /root/.local/share/virtualenvs/src-uOgj0FIk/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
>     warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

**Comment by d1618033** [comment]
@jaraco I released a new version. I am sorry for the massive delay.
