### ISSUE TITLE
Cannot import Munch if the wheel doesn't come from a regular source

### ISSUE THREAD

**Issue by sebastienwood** [Infinidat/munch#75]
Hi !
Munch is a dependancy in a project of mine. When loaded in an env. where the wheels are locally provided, it cannot be imported properly as we see in the following traceback:

> Traceback (most recent call last):
  File "/home/script.py", line 7, in <module>
    import munch
  File "/localscratch/temp_instance/env/lib/python3.8/site-packages/munch/__init__.py", line 29, in <module>
    VERSION = tuple(map(int, __version__.split('.')[:3]))
ValueError: invalid literal for int() with base 10: '0+computecanada'

**Comment by mdornseif** [comment]
I observe similar issues in an pipenv: `ValueError: invalid literal for int() with base 10: 'unknown'`
