### ISSUE TITLE
New version on PyPi with RecursiveMunch

### ISSUE THREAD

**Issue by thomasjbradley** [Infinidat/munch#78]
Could we get a new version deployed to PyPi with all the `RecursiveMunch` stuff in it?

Thanks!

**Comment by Lego3** [comment]
I wonder whether this project is dead? @d1618033 is the latest one to commit anything. Do you know whether we can expect some release?

**Comment by santoshphilip** [comment]
My sense is that this is a stable project. It would not get too many changes at this point.
My project [eppy](https://github.com/santoshphilip/eppy) is very dependent on munch.
I get nervous when there are a lot of changes in munch :-)

**Comment by d1618033** [comment]
@Lego3 @thomasjbradley I deployed a new version (3.0.0) with the RecursiveMunch and other goodies 🙂 
@santoshphilip you can pin the version of munch to "<3.0.0" in your requirements file if you don't want the recent changes

**Comment by santoshphilip** [comment]
thanks @d1618033 , I'll test eppy with the latest version of munch. If all goes well, I'll go with the latest.
