### ISSUE TITLE
Munch cannot recursively fetch values beyond first level when passed with a dot notation.

### ISSUE THREAD

**Issue by GeorgeDavis-TM** [Infinidat/munch#79]
I am trying to read a config file in JSON and fetch values using Munch object notation. I am able to fetch first level keys using `d['region']` and it returns `{'api_key': 'abcdefgh'}` but when I query `d['region.api_key']`, DefaultMunch returns `None`.

Expected behaviour: `d['region.api_key']` returns `'abcdefgh'`.

Can Munch recursively fetch values? Please advise.

I am using Munch from PyPi, v2.5.0

### config.json
     { 'name': 'test', 'region': {'api_key': 'abcdefgh'}}

### main.py
    def get_config_from_file(config_key):

        f = open('config.json', 'r+')
        json_object = json.loads(f.read())
    
        if "." in config_key: # for example, config_key is 'region.api_key', then Munch!
            d = DefaultMunch.fromDict(json_object)
            print("Munch: " + str(d[config_key]))
            return d[config_key]
    
        elif json_object[config_key]: # for example, config key is a simple 'name', then access Dict normally
            return str(json_object[config_key])
        return ""`

    if __name__ == "__main__":
        get_config_from_file('region.api_key')

**Comment by d1618033** [comment]
Munch doesn't support dot notation within the key string. 
So a.b.c works but a["b.c"] does not and there are no plans to make it work. 
There are other libraries that do support this, eg check out glom: https://glom.readthedocs.io/en/latest/

**Comment by GeorgeDavis-TM** [comment]
Unless I am aware of the traversal path, I will not be able to use munch, is that correct? I am unable to take the traversal path as function argument and execute it with munch.

I have `data = DefaultMunch.fromDict(json_object)`. `config_key` is the path in `data` I want to fetch. 

Example: `region.api` is the traversal path. I am unable to assemble `data.region.api_key` and then executing it. Do you have any examples of how I should write this in Python without prior knowledge of the traversal path?
 
 Usecase: I am writing a function that takes a JSON file and can fetch Dict key-value pairs using the function arguments.
