### ISSUE TITLE
mucnh does not seem to work when called using python's exec method 

### ISSUE THREAD

**Issue by elliot-eichen** [Infinidat/munch#80]
Hi:

Perhaps I am dong something wrong here - trying to execute a munch statement written as text using exec('text').  Does not seem to work.  Per the attached yaml file, devices.GPIO18.type should be "door."  When executed using exec it comes back as "None.":  
```
print(devices.GPIO18.type)
print(exec('devices.GPIO18.type'))
```
yields:

>>> %Run test.py
```
door
None
```
I've attached the yaml file and the code. Many thanks - Elliot
[alarmDevices.txt](https://github.com/Infinidat/munch/files/9388237/alarmDevices.txt)
[test.py.txt](https://github.com/Infinidat/munch/files/9388240/test.py.txt)

**Comment by d1618033** [comment]
You should use eval not exec
